### PR TITLE
Challenge

### PR DESCRIPTION
**Pull request by thejonroberts**
Should be good to go!

### CODE REVIEW

**Comment by thejonroberts** [comment]
restructuring to make tree function accept object argument, as per instructions!  This push does not do that. 👎

**Comment by thejonroberts** [comment]
tree now using the object and passing it along.  I believe requirements have now been met.

**Comment by thejonroberts** [comment]
haha.  just kidding.  i was still skirting around using the object.

**Comment by thejonroberts** [comment]
okay, ready for feedback for real this time!

**Comment by JoeShep** [comment]
Jon, this works just as expected. You also have some nice checks for good input from your user. 
The logic for getting the tree logged out to the console is a bit more convoluted than it needs to be, but that's a minor quibble. Very nice work.
👍

**Pull request merged**
